import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { format, formatDistanceToNow } from 'date-fns';
import { requireUser } from '@/lib/auth/session';

type Params = { params: Promise<{ id: string }> };

// GET /api/goals/[id]/export
// Exports a goal as a Markdown document — useful for sharing, journaling,
// or archiving a completed goal. Returns text/markdown.
// Scoped to the authenticated user.
export async function GET(_req: NextRequest, { params }: Params) {
  const userIdOrResponse = await requireUser();
  if (userIdOrResponse instanceof NextResponse) return userIdOrResponse;
  const userId = userIdOrResponse;

  const { id } = await params;
  const goal = await db.goal.findFirst({
    where: { id, userId },
    include: {
      tasks: {
        include: {
          scheduleBlocks: { orderBy: { startAt: 'asc' } },
          progressLogs: { orderBy: { loggedAt: 'asc' } },
        },
        orderBy: { orderIndex: 'asc' },
      },
      availability: { orderBy: { createdAt: 'asc' } },
      riskAssessments: { orderBy: { assessedAt: 'desc' }, take: 5 },
    },
  });
  if (!goal) {
    return NextResponse.json({ error: 'Goal not found' }, { status: 404 });
  }

  const lines: string[] = [];
  lines.push(`# ${goal.title}`);
  lines.push('');
  lines.push(`> Exported from Last Minute Pilot on ${format(new Date(), 'd MMM yyyy, h:mm a')}`);
  lines.push('');

  // Meta
  lines.push('## Overview');
  lines.push('');
  lines.push(`- **Status:** ${goal.status}`);
  lines.push(`- **Type:** ${goal.goalType === 'habit' ? 'Habit' : 'One-time goal'}`);
  if (goal.category) lines.push(`- **Category:** ${goal.category}`);
  if (goal.deadline) {
    lines.push(`- **Deadline:** ${format(goal.deadline, 'd MMM yyyy, h:mm a')} (${formatDistanceToNow(goal.deadline, { addSuffix: true })})`);
  } else {
    lines.push(`- **Deadline:** none`);
  }
  lines.push(`- **Created:** ${format(goal.createdAt, 'd MMM yyyy')}`);
  lines.push('');

  // Raw input
  if (goal.rawInput) {
    lines.push('## Description');
    lines.push('');
    lines.push(goal.rawInput);
    lines.push('');
  }

  // Tasks
  const totalTasks = goal.tasks.length;
  const doneTasks = goal.tasks.filter((t) => t.status === 'done').length;
  const progress = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;
  lines.push('## Tasks');
  lines.push('');
  lines.push(`Progress: ${doneTasks}/${totalTasks} done (${progress}%)`);
  lines.push('');
  for (const task of goal.tasks) {
    const check = task.status === 'done' ? '[x]' : task.status === 'skipped' ? '[-]' : '[ ]';
    lines.push(`- ${check} **${task.title}** (${task.estimatedMinutes}m)`);
    if (task.description) lines.push(`  ${task.description}`);
    // Schedule blocks
    if (task.scheduleBlocks.length > 0) {
      for (const b of task.scheduleBlocks) {
        lines.push(`  - ${format(b.startAt, 'd MMM h:mm a')} – ${format(b.endAt, 'h:mm a')} (${b.status})`);
      }
    }
    // Progress logs
    if (task.progressLogs.length > 0) {
      for (const log of task.progressLogs.slice(-3)) {
        lines.push(`  - ${format(log.loggedAt, 'd MMM h:mm a')}: ${log.percentComplete}%${log.note ? ` — ${log.note}` : ''}`);
      }
    }
  }
  lines.push('');

  // Availability
  if (goal.availability.length > 0) {
    const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    lines.push('## Availability');
    lines.push('');
    for (const a of goal.availability) {
      if (a.dayOfWeek !== null) {
        lines.push(`- ${days[a.dayOfWeek]} ${a.startTime}–${a.endTime}`);
      } else if (a.specificDate) {
        lines.push(`- ${format(a.specificDate, 'd MMM yyyy')} ${a.startTime}–${a.endTime}`);
      }
    }
    lines.push('');
  }

  // Risk history
  if (goal.riskAssessments.length > 0) {
    lines.push('## Risk History');
    lines.push('');
    for (const r of goal.riskAssessments) {
      lines.push(`### ${r.riskLevel.toUpperCase()} — ${format(r.assessedAt, 'd MMM h:mm a')}`);
      lines.push('');
      if (r.reason) {
        lines.push(r.reason);
        lines.push('');
      }
      if (r.suggestedAction) {
        lines.push(`**Suggested action:** ${r.suggestedAction}`);
        lines.push('');
      }
      lines.push(`_Work: ${r.remainingWork}m · Free time: ${r.remainingTime}m_`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('_Generated by Last Minute Pilot — AI copilot for deadlines._');

  const markdown = lines.join('\n');
  const safeTitle = goal.title.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 50);

  return new NextResponse(markdown, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="${safeTitle}.md"`,
    },
  });
}
